# Generated by Django 3.1 on 2022-01-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='user_name',
            new_name='username',
        ),
    ]
